services:
  deploy-hook:
    build: .
    container_name: deploy-hook
    restart: unless-stopped
    ports:
      - "9061:9061"
    volumes:
      - /home/ubuntu/gymlete-docker:/repos
      - /var/run/docker.sock:/var/run/docker.sock
